# -*- coding: utf-8 -*-
"""MF Tool Python Library

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ttdUZeZ7RCLNV5fclVMt3Mg_YeJntHm-

**MFTool Python Library:**
mftool is a library for getting real time Mutual Funds data in India. It can be used in various types of projects which requires getting live quotes for a given mutual fund scheme or build large data sets for further data analytics.

What is Mutual Fund:

Mutual Funds pool money from investors and then invest them in a basket of securities such as stocks, bonds, debt, etc.
An investor can invest in a Mutual Fund by buying its units and can earn a profit/loss by selling these units at a higher/lower price. The price of these units is called NAV(Net Asset Value) and is determined by the AUM(Assets under Management) and the units issued.
"""

!pip install mftool

from mftool import Mftool

mf = Mftool()
print(mf)

all_schemes = mf.get_scheme_codes()
print(all_schemes)

Scheme_code = '149389'

details = mf.get_scheme_details(Scheme_code)
print(details)

q = mf.get_scheme_quote(Scheme_code)
print(q)

historical_data = mf.get_scheme_historical_nav(Scheme_code, as_Dataframe=True)

historical_data.head()

historical_data.tail()

historical_data.describe()

historical_data.isna()

import pandas as pd
import numpy as np

from os import name
list1 = ['149389','149072','149463','143247','128627']
df1 = pd.DataFrame()
for i in list1:
    historical_data = mf.get_scheme_historical_nav(i, as_Dataframe=True)
    name=mf.get_scheme_details(i)['scheme_name']
    df1[name] = historical_data['nav']

df1

av_aum = mf.get_average_aum('July - September 2024',False)
av_aum

import seaborn as sns
import matplotlib.pyplot as plt

mutual_fund_code = '118989'
mutual_fund = 'HDFC Mid-Cap Opportunities Fund - Growth Option - Direct Plan'

df = mf.get_scheme_historical_nav(mutual_fund_code,as_Dataframe=True).reset_index()
df['nav'] = df['nav'].astype(float)
df['date'] = pd.to_datetime(df['date'], format='%d-%m-%Y')
df = df.sort_values('date').reset_index(drop=True)
display(df)
df.plot(x='date', y='nav')
plt.title(mutual_fund)





